# Generated by Django 5.2.6 on 2025-09-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20, verbose_name='Пол')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('skills', models.CharField(help_text='Перечислите навыки через запятую', max_length=250, verbose_name='Навыки')),
                ('level_sills', models.CharField(help_text='от 1 до 10', max_length=250, verbose_name='Уровень навыков')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
