# Generated by Django 5.2.6 on 2025-09-24 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('workplace', '0002_rename_employee_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='workplace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='workplace.workplace', verbose_name='Рабочее место'),
        ),
    ]
