# Generated by Django 5.2.7 on 2025-10-12 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_workplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='employees/gallery/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядковый номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='employee.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Изображение сотрудника',
                'verbose_name_plural': 'Изображения сотрудников',
                'ordering': ['order', 'created_at'],
                'unique_together': {('employee', 'order')},
            },
        ),
    ]
