# Generated by Django 5.2.7 on 2025-10-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='level_sills',
            new_name='level_skills',
        ),
        migrations.AddField(
            model_name='employeeimage',
            name='title',
            field=models.CharField(blank=True, help_text='Необязательное описание изображения', max_length=200, verbose_name='Название изображения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='employeeimage',
            name='image',
            field=models.ImageField(upload_to='employees/gallery/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
