[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | venv
)/
'''
extend-exclude = '''
/migrations/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_first_party = ["myproject", "myapp", "books", "accounts", "utils"]
known_django = ["django"]
skip_glob = ["*/migrations/*", "*/__pycache__/*"]
known_third_party = ["django", "requests", "pillow"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"

[tool.isort.project_directories]
"./" = "FIRSTPARTY"
"./myapp" = "FIRSTPARTY"
"./books" = "FIRSTPARTY"
"./accounts" = "FIRSTPARTY"